version: '3.5'

services:
  app:
    build:
      context: '.'
    container_name: stand-app
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www/html
    networks:
      - default
    links:
      - db

  db:
    image: mysql:5.6
    container_name: stand-app_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - "3306:3306"
    volumes:
          - ./run/var:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      default:
        aliases:
          - ${APP_DOMAIN}
